"""add major to academic_history

Revision ID: ed72ef60c214
Revises: d7d3de3ae16a
Create Date: 2025-09-26 13:05:45.203186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed72ef60c214'
down_revision: Union[str, Sequence[str], None] = 'd7d3de3ae16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_history', sa.Column('major', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_history', 'major')
    # ### end Alembic commands ###
